"""adiciona novos dados a biografia

Revision ID: 12e885a86b47
Revises: 36129f7028fb
Create Date: 2026-01-19 08:26:58.458809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e885a86b47'
down_revision = '36129f7028fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biography', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biography', schema=None) as batch_op:
        batch_op.drop_column('endereco')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('instagram')

    # ### end Alembic commands ###
