"""ajusta o nome da tabela de biografia

Revision ID: 36129f7028fb
Revises: 22d086dcdcc7
Create Date: 2025-12-26 20:18:59.853047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36129f7028fb'
down_revision = '22d086dcdcc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biography',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biography')
    # ### end Alembic commands ###
