"""adiciona id do google na tabela usuario

Revision ID: 8db92194ea9a
Revises: 
Create Date: 2025-11-18 09:11:30.405422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8db92194ea9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [c['name'] for c in inspector.get_columns('users')]
    if 'google_id' not in columns:
        with op.batch_alter_table('users') as batch_op:
            batch_op.add_column(sa.Column('google_id', sa.String(255)))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
